version: '3'

services:
  django:
    build: ../backend_django
    container_name: django_api
    ports:
      - "8000:8000"
    volumes:
      - ../backend_django:/app
    environment:
      - PYTHONUNBUFFERED=1
      - STRIPE_SECRET_KEY=sk_test_51QqCx7DzvfiQtQhxAogrZaGS6or1LwpT6QZHj88z2Tvg4hNUEvfZH3KYaFDon86NvaZdmt3AyddGTxWt7ULeDkeu006CLLRYLA
      - STRIPE_PUBLIC_KEY=pk_test_51QqCx7DzvfiQtQhxxlDLv4OBxkqoHUek9iQs5NmjIx2yO0VrtjIIcYmGb1yNKdAZDHuZhmBVOzqN5mCmObEJd3q500Zb9hlDa5
    depends_on:
      - mysql_db  

  spring_api:
    build: ../backend_spring
    container_name: spring_api
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/spring_db?useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=springuser
      - SPRING_DATASOURCE_PASSWORD=springpass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - STRIPE_SECRET_KEY=sk_test_51QqCx7DzvfiQtQhxAogrZaGS6or1LwpT6QZHj88z2Tvg4hNUEvfZH3KYaFDon86NvaZdmt3AyddGTxWt7ULeDkeu006CLLRYLA
    depends_on:
      - mysql_db

  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    depends_on:
      mysql-db:
        condition: service_healthy
    restart: always
    networks:
      - mi_red

  stripe-servicio:
    build: ./stripe-payment-service
    ports:
      - "8083:8083"
    depends_on:
      mysql-db:
        condition: service_healthy
    restart: always
    networks:
      - mi_red

  paypal-servicio:
    build: ./paypal-service
    ports:
      - "8084:8084"
    depends_on:
      mysql-db:
        condition: service_healthy
    restart: always
    networks:
      - mi_red

  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spring_db
      MYSQL_USER: springuser
      MYSQL_PASSWORD: springpass
    ports:
      - "3307:3306"  
    volumes:
      - mysql_data:/var/lib/mysql

      

volumes:
  mysql_data:

networks:
  mi_red:
    driver: bridge
