version: '3'

services:
  django:
    build: ../backend_django
    container_name: django_api
    ports:
      - "8000:8000"
    volumes:
      - ../backend_django:/app
    environment:
      - PYTHONUNBUFFERED=1
      - STRIPE_SECRET_KEY=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  # Reemplaza con tu clave secreta de test
    depends_on:
      - mysql_db  

  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spring_db
      MYSQL_USER: springuser
      MYSQL_PASSWORD: springpass
    ports:
      - "3307:3306"  
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
